[main]
Title=Resource Hacker
Description=Resource Hacker 5.1.7 is a resource editor for 32bit and 64bit Windows applications. It's both a resource compiler (for *.rc files), and a decompiler - enabling viewing and editing of resources in executables (*.exe; *.dll; *.scr; etc) and compiled resource libraries (*.res, *.mui).
Selected=True
Level=5
Version=1
Download_Level=0
NoWarning=False
Date=20.08.2020
Author=2CongLC.Vn

[variables]
%ProgramTitle%=Resource Hacker
%ProgramEXE%=ResourceHacker.exe
%ProgramFolder%=Resource Hacker

[Interface]
pCheckBox2="Desktop Shortcut",1,3,18,43,200,18,True
pCheckBox1="Run from RAM (boot.wim) - Recommended",1,3,19,18,264,18,True
pCheckBox3="StartMenu : ",1,3,19,66,80,18,False
pTextBox1="StartMenu Folder",1,0,24,106,200,21,

[process]
If,%pCheckBox1%,Equal,True,Begin
  DirMake,"%Target_Prog%\%ProgramFolder%\"
  If,%SourceArch%,Equal,x86,Begin
    DirCopy,"%ScriptDir%\xall\*.*","%Target_Prog%\%ProgramFolder%\"
  End
  If,%SourceArch%,Equal,x64,Begin
    DirCopy,"%ScriptDir%\xall\*.*","%Target_Prog%\%ProgramFolder%\"
  End
  Run,%ScriptFile%,Add_Shortcuts
  Run,%ScriptFile%,Add_Registry
End

[Add_Shortcuts]
If,%pCheckBox2%,Equal,True,Add_Shortcut,Desktop
If,%pCheckBox3%,Equal,True,Add_Shortcut,StartMenu,%pTextBox1%

[Add_Registry]
//0x1 = String, 0x2 = Expand String, 0x3 = Binary Data, 0x4 = Dword
